### ISSUE TITLE
remove old cache

### ISSUE THREAD

**Issue by maninhat** [liip/LiipImagineBundle#1156]
Is there a way to delete all cache files older than a some date?

**Comment by robfrawley** [comment]
You would have to manually extend the relevant services and iterate through all your images (checking their modification date/time) to achieve such functionality. Otherwise, there is no native option to perform this operation. A simpler method would likely be to simply go into your cache directory and use the [find command](http://man7.org/linux/man-pages/man1/find.1.html) to locate all files with modification times older than a certain number of days.
