### ISSUE TITLE
Retina support

### ISSUE THREAD

**Issue by bartlomiej84** [liip/LiipImagineBundle#123]
I was wondering what would be the easiest way to add support for Retina display. What functionality I should add ? I don't want to modify bundle, I only want to replace some managers, or maybe a controller, but I have no idea where is the best place to start.

I would like this bundle to make 2 cached images with different resolutions (second twice bigger as first), in the same cached directory and off course with suffix to filename like `@2x`, so it can be supported by Retina.js. 

Any help would be appreciate. 
Thanks.

**Comment by kironet** [comment]
What about 2017? Is retina supported?

**Comment by lsmith77** [comment]
again from my point of view the approach to generate 2 images at once is wrong. whatever you do on the frontend (ie. css/js) simply has to reference the images with the relevant configuration to resize accordingly. so the topic is imho beyond the scope of this Bundle.

see also `srcset` attribute

**Comment by havvg** [comment]
I neither see any issue for this bundle regarding retina support, @kironet. This issue has been closed over 4 years ago and the bundle is capable of rendering images since the beginning. It's only up to you, to support your retina requirements; see my previous comment for one possible solution.

From the perspective of an image, there is no "retina support". "Retina" merely "uses" a different resolution of an image being shown. If you upload an image with `4000x4000px` with `72ppi` resolution, then that's the "normal" one. If you want a retina version of it, you would require a `8000x8000px` version of the very same image and render it with e.g. `144ppi`, which would result in a `4000x4000px` display size. If you want the same image to be available at `288ppi`, then you would be required to upload a `16000x16000px` at `72ppi`. 

As you can see, there are multiple options to resolve this. I would recommend you to upload the highest resolution you have and render the lower resolutions at the target image size. For example when your requirement is having a `4x`, `2x` and `1x` resolution version of the image while preserving the display size, you would require to upload the `4x` one. Let's say you upload a `100x100px` at `288ppi`. That's your `4x` version. Now you can setup two filters to yield the `2x` and `1x` resolution version of it. You would need to set the resolution to `144ppi`, which first yields an image of size `200x200px` and then you scale it down to `100x100px`. The second filterset just does the same but with `72ppi` respectively to yield the `1x` version.
