### ISSUE TITLE
Liip + KnpGaufrette + Google Cloud Service : slow performances

### ISSUE THREAD

**Issue by ludovicpages** [liip/LiipImagineBundle#1288]
Hello. 
I'm successfully using Google Cloud Service with Liip and Kip Gaufrette. 
Doing a `{{image.jpg|imagine_filter( 'my_filter' )}}` generates the filtered image on a cache folder on the GCS bucket. Works fine.

The problem I'm facing, is that even when the filtered images exists on the cache folder on the GCS bucket, it takes a long time for the image to be displayed. I kind of understand why, back and force between my server and GCS ( checking if object exists, then returning the objet from who i can build the object Url.

If I'm calling the URL directly, it's fast and furious.

Maybe I'm missing something, am I suppose to add a layer on top of that config ? 
And storing the urls in a cache locally ? 

I think I'm missing something here :) 

Thanks.

**Comment by przemyslawkliktu** [comment]
Hi,

could you share your config?

**Comment by Warxcell** [comment]
Try https://symfony.com/doc/current/bundles/LiipImagineBundle/cache-resolver/cache.html#cache-resolver-cache

**Comment by oliver-schulz** [comment]
The problem here is when you want to return a url or a resolve url to your frontend the bundle checks first if the image in the given filter configuration is already created, if not the filter generates one cached image. The problem here that you have to ask every time the google api if there is a cached images and the response times from google api are "slow". So if you have to render several images, eg. product list, the server time gets even longer, in our case we had to render about 52 images and every api call needed about 30ms for each images, so we "waited" 1.5 seconds for asking google if there is a cached image :)

We "solved" it by using a redis cache which stores all the generated images for us, so we don't have to ask google first.

**Comment by peter-gribanov** [comment]
The problem can be solved by warming up the cache and always using a link to the cache in the templates without hecking for availability #1348

**Comment by ludovicpages** [comment]
Thanks guys. 
Same as @oliver-schulz we hacked it by storing the images with filter on Memcached.
