### ISSUE TITLE
League\Flysystem\WebDAV\WebDAVAdapter does not support visibility settings

### ISSUE THREAD

**Issue by max4kaps** [liip/LiipImagineBundle#1289]
Liip\ImagineBundle\Imagine\Cache\Resolver\FlysystemResolver forces visibility VISIBILITY_PUBLIC on flysystem that causes an exception on flysystem adapters not supporting visibility. For example league/flysystem-webdav.

### Preconditions
liip_imagine using flysystem filesystem with adapter webdav. If you don't specify any visibility, visibility=public is passed to the adapter, this causes an exception.

### Expected result
Symfony: 4.4
# composer
    "require": {
        "liip/imagine-bundle": "^2.1",
        "oneup/flysystem-bundle": "^3.4",
        "twistor/flysystem-stream-wrapper": "dev-master#3f90145d4016f826ad80cf921550cda2c68c4402",
        "league/flysystem-webdav": "^1.0",
}

### Actual result

![image](https://user-images.githubusercontent.com/1004349/85285447-3fb05600-b491-11ea-811f-f073e24da2cd.png)

**Comment by dbu** [comment]
does flysystem have a capability check system? if so, we could change the FlysystemResolver constructor to default the visibility to `null`, check if the flysystem supports visibility and if so, use the default, otherwise keep it null and check in `store` to not configure visibility if it is null. and if a visibility value is specified in the constructor arguments but flysystem does not support visibility, throw an exception to report that visibility is not possible with the given adapter (i prefer being explicit over silently ignoring that parameter).

do you want to do a pull request with that?

**Comment by dbu** [comment]
this has been fixed in #1389, a release is pending but should happen soon.
