### ISSUE TITLE
How to securize cached images

### ISSUE THREAD

**Issue by davidromani** [liip/LiipImagineBundle#1371]
Hello, I've been googling how to protect or secure cache images and I don't see how to do it. So, first of all, my apologies if this is not the right place to ask it but maybe someone can show me a hint to achieve it.

And I want to store the cached images rendered by LiipImagineBundle under a secured path that everybody must be authenticated before with a ROLE_ADMIN permission.

I think that it shall be an out-of-box feature, but I don't understand how to do it. Thanks.

**Comment by dbu** [comment]
hi david, sorry for the late reply. i am going through the backlog of issues and look into things.

the use case of this bundle is to handle public images. the images, once cached, are served directly from the filesystem and don't go through symfony.

you could however configure your webserver to not check if the files exist but go to a symfony controller (that you would have to build) that would then deliver the file if permissions are fine. with nginx, there is the X-Accel mechanism you can use: https://www.nginx.com/resources/wiki/start/topics/examples/x-accel/ (first answer of https://stackoverflow.com/questions/31516918/nginx-and-php-how-do-you-only-allow-a-file-download-under-a-certain-condition has an example how to use it - you'd do a symfony controller instead of the plain php script in the example)
