### ISSUE TITLE
Download the Bundle invalid path 'Tests/Functional/app/public/images/cat?question.jpeg'

### ISSUE THREAD

**Issue by Dominik2786l** [liip/LiipImagineBundle#1435]
### Preconditions

1. Windows 10
2. PHP 7.3, symfony 5

### Steps to reproduce

1. i  only run command "composer require liip/imagine-bundle"

### Expected result

1. download bundle :D

### Actual result

1. [Screenshot, logs]
![image](https://user-images.githubusercontent.com/95223073/143865480-36681383-7df6-4ff6-85e8-c76ae45184e3.png)

**Comment by dbu** [comment]
these files exist to test some edge cases about filenames: https://github.com/liip/LiipImagineBundle/tree/2.x/Tests/Functional/app/public/images

i guess this means that the filesystem you are using is not capable of handling such a filename. can you switch to use the `dist` instead of the `source` for liip imagine? in the git attributes, the Tests folder is excluded: https://github.com/liip/LiipImagineBundle/blob/2.x/.gitattributes#L4

afaik you can remove the vendor/liip/imagine-bundle folder from your filesystem, then run `composer install --prefer-dist` to install the imagine bundle as dist rather than clone the whole repository.
