### ISSUE TITLE
Filter function to return the image instead of a redirect to the image (for SEO reasons)

### ISSUE THREAD

**Issue by AdamReece-WebBox** [liip/LiipImagineBundle#1471]
Hello,

We've been getting a lot of moaning from our SEO partners regarding images being served via redirects. I don't know the ins and outs as I'm not an SEO expert, but from what I gather this is harmful because it's creating extra unnecessary HTTP requests, and Google (and rivals) penalise your SEO scoring because of this.

We typically produce a `<picture>` with multiple `<source>` using `imagine_filter`. The resulting URL is fine, but visiting it returns a redirect response instead of the image produced. Is it possible for the filter controller to return the image data instead of a redirect to it for the benefit of SEO? Even if it were to use an internal Symfony forwarder that would be great. (Perhaps this is an option already I've missed?)

This is mainly important for production environment, though in developer environment we already have `intercept_redirects` off for the web profiler.

To be clear though, this component is working well and doing a brilliant job with image outputs. Our page speed scores have improved noticeably since we started using it to thumbnail images in multiple responsive formats.

Possibly related:
https://github.com/liip/LiipImagineBundle/issues/77
https://github.com/liip/LiipImagineBundle/issues/465

Thanks,
Adam

**Comment by dbu** [comment]
hi @AdamReece-WebBox , glad to hear that the component works well for you! the redirection is done when the image does not exist in the cache. it is done this way to let the web server deliver static image files, rather than piping image data through the symfony application. even if we would support [x-sendfile/x-accel](https://www.nginx.com/resources/wiki/start/topics/examples/xsendfile/), this path would still need to bootstrap the symfony application each time it requesting, and at least look at the image file (i am not sure if its unconditionally recreating the image then, or checking if it is necessary to recreate it, would need to investigate that).

i think the best way to avoid the redirections on a cold cache is to warmup the cache. it takes some effort from your side, as the bundle can't know what images exist - if you have a cms-ish application with image upload, dispatch messages on image upload: https://symfony.com/bundles/LiipImagineBundle/current/optimizations/resolve-cache-images-in-background.html . if you have images that are deployed with the code, you could either write a deployment script to generate messages as well, or directly generate the images with the warmup cli command: https://symfony.com/bundles/LiipImagineBundle/current/commands.html#warm-up-cache (if you have lots of images, i would recommend messenger and workers to not block the deployment and to parallelize the work. even if not all images are done when the application goes online, they will be done eventually and you might get a few redirects right after deployment as necessary, but all will work from a user perspective)

**Comment by AdamReece-WebBox** [comment]
Hi dbu,

Thanks for your response. (I was 99% sure I posted a reply last week, but nope it's not here!)

> the redirection is done when the image does not exist in the cache. it is done this way to let the web server deliver static image files, rather than piping image data through the symfony application.

Personally, on performance terms, I agree with this approach. That's always going to be faster than the Symfony application being involved and having to just bridge through a streamed response.

> (i am not sure if its unconditionally recreating the image then, or checking if it is necessary to recreate it, would need to investigate that).

From what I've experienced it doesn't look like images are being unconditionally regenerated.

Whenever someone on our team creates or updates a page we instruct them to look at the live front end view of it, not only to sense check it, but also to warm up the image cache. On the first visit the images being lazy loaded in are noticeably delayed whilst being generated. (PHP's CPU usage server side is a clear indicator of that roaring away.) However subsequent visits, be it on the same browser or a different one devoid of cache, are more or less instant. (Even though there's a redirect.)

--

This literally boils down to the SEO partner not liking the fact that the image sources are returning a 301 redirect to the physical file instead of just serving the physical file directly. A streamed response would resolve that, though as we've mentioned this would have a slight performance hit whilst Symfony delivers that stream.

Perhaps from my side the question would be whether we're making proper use of the `imagine_filter` filter. We've got a Twig macro to produce a responsive image in multiple formats.

The exact macro probably isn't important, though calling `imagine_filter` with the same image and options produces a consistent URL, for example:
```
/media/cache/resolve/thumb/rc/DhS7ooib/image/page/our-story.jpg?filters%5Bthumbnail%5D%5Bsize%5D%5B0%5D=400&filters%5Bthumbnail%5D%5Bsize%5D%5B1%5D=300
```

When that URL is invoked the image is produced (if not already) then redirected to a URL such as:
```
/image_cache/thumb/rc/DhS7ooib/image/page/our-story.jpg.webp
```

Should we still be calling `imagine_filter` for images that have already generated?
I guess this would mean the filter would need to check the file system for the image instead of what I assume is just building a URI for inserting into the HTML.

The full macro typically takes in one image web URI `image` as follows:
```twig
{% macro respImg(image, options) %}
    {% set optionsDefault = {
        sizes:          [120, 240, 360, 640, 768, 992, 1200, 1366, 1920],
        lazy:           true,
        ratio:          false,
        bg:             false,
        alt:            null,
        classes:        "",
        noDefaultSize:  false,
    } %}

    {% set imageAsset   = asset(image) %}
    {% set imageObject  = web_image(image) %}

    {% if imageAsset and imageObject %}
        {% set options      = options ? optionsDefault|merge(options) : optionsDefault %}
        {% set alt          = fileManager.metaValueWebPath(image, ["alt", "name"], options.alt) %}
        {% set outputWidths = options.noDefaultSize or options.sizes|length == 1 ? options.sizes : options.sizes|merge([imageObject.width]) %}
        {% set src          = [] %}
        {% set srcSet       = {
            webp:   [],
            jpeg:   [],
            native: [],
        } %}

        {# Generate thumbnails smaller than the original image (width) #}
        {% for outputWidth in outputWidths if outputWidth <= imageObject.width %}
            {% set outputHeight             = options.ratio ? outputWidth * options.ratio : outputWidth %}
            {% set imageTransformOptions    = {thumbnail: {size: [outputWidth, outputHeight]}} %}

            {% for srcSetType, imageThumb in {
                webp:   imageAsset|imagine_filter('thumb_webp', imageTransformOptions),
                jpeg:   imageAsset|imagine_filter('thumb_jpeg', imageTransformOptions),
                native: imageAsset|imagine_filter('thumb',      imageTransformOptions),
            } %}
                {% if srcSetType == "native" %}
                    {% set src = src|merge([imageThumb]) %}
                {% endif %}
                {% set srcSetForType = srcSet[srcSetType]|merge([imageThumb ~ ' ' ~ outputWidth ~ 'w']) %}
                {% set srcSet = srcSet|merge({(srcSetType): srcSetForType}) %}
            {% endfor %}
        {% endfor %}

        {# Build <picture> tag #}
        {% if src is iterable and src|length >= 1 and srcSet is iterable and srcSet.native is defined and srcSet.native is iterable and srcSet.native|length >= 1 %}
            <picture>
                {% if srcSet.native|length >= 2 %}
                    {# Multiple image sizes #}
                    {% if options.lazy %}
                        {# Lazy loaded #}
                        {% for srcSetType, srcSetForType in srcSet if srcSetForType|length >= 2 %}
                            <source {% if srcSetType != "native" %} type="image/{{ srcSetType }}" {% endif %} data-srcset="{{ srcSetForType|join(', ') }}" data-srcset-type="{{ srcSetType }}"/>
                        {% endfor %}
                        <img data-src="{{ src[0] }}" data-srcset="{{ srcSet.native|join(', ') }}" alt="{{ alt }}" class="lazy {{ options.classes }}"/>
                    {% else %}
                        {# Eagar loaded #}
                        {% for srcSetType, srcSetForType in srcSet if srcSetForType|length >= 2 %}
                            <source {% if srcSetType != "native" %} type="image/{{ srcSetType }}" {% endif %} srcset="{{ srcSetForType|join(', ') }}" data-srcset-type="{{ srcSetType }}"/>
                        {% endfor %}
                        <img src="{{ src[0] }}" srcset="{{ srcSet.native|join(', ') }}" alt="{{ alt }}" class="loaded {{ options.classes }}"/>
                    {% endif %}
                {% else %}
                    {# Only 1 image size #}
                    {% if options.lazy %}
                        {# Lazy loaded #}
                        {% for srcSetType, srcSetForType in srcSet if srcSetForType|length == 1 %}
                            <source {% if srcSetType != "native" %} type="image/{{ srcSetType }}" {% endif %} data-src="{{ srcSetForType[0] }}" data-src-type="{{ srcSetType }}"/>
                        {% endfor %}
                        <img data-src="{{ src[0] }}" alt="{{ alt }}" class="lazy {{ options.classes }}" width="{{ imageObject.width }}" height="{{ imageObject.height }}"/>
                    {% else %}
                        {# Eagar loaded #}
                        {% for srcSetType, srcSetForType in srcSet if srcSetForType|length == 1 %}
                            <source {% if srcSetType != "native" %} type="image/{{ srcSetType }}" {% endif %} srcset="{{ srcSetForType[0] }}" data-srcset-type="{{ srcSetType }}"/>
                        {% endfor %}
                        <img src="{{ src[0] }}" alt="{{ alt }}" class="loaded {{ options.classes }}" width="{{ imageObject.width }}" height="{{ imageObject.height }}"/>
                    {% endif %}
                {% endif %}
            </picture>
        {% endif %}
    {% endif %}
{% endmacro %}
```

(We're using our in house CMS so we can make any reasonable amendment.)

**Comment by dbu** [comment]
the twig filter goes to the cache manager at https://github.com/liip/LiipImagineBundle/blob/665b6a673b2ddfa96a2941467a799c5adaceb4f6/Imagine/Cache/CacheManager.php#L109 which in turn checks if the requested image exists in the cache (`isStored`) and if it is, it goes to the resolver of the stack to ask it for the url (this is indirect because you might be storing the rendered images in an S3 bucket or similar, not necessarily on the same domain as the web application).

so if you warmup the cache with the stack and all options as you use them later, there should be no redirect but a direct path to the image. however, when the cache is warmed on the fly, the html that is generated has to point to the controller that will do the redirect. if the final html is cached, this will stay the same until the html cache expires.

when warming up the cache, you would need to provide the same list of parameters as you do in the template, as the cache warmup mechanism can't know what options you will be using. alternatively, you could define one stack per size and warmup each size, but then the warmup would need to know each stack name, so not much different. you would be moving the logic from twig into the stack configuration, but then your frontend still needs to know which stack means what to use the right image.

little spam note: another radically different approach could be to use a 3rd party service like rokka.io to handle the image conversion. there you would not have redirects ever, and it comes integrated into a CDN for optimal image delivery.

**Comment by AdamReece-WebBox** [comment]
Hi dbu,

Thanks again for the insight. I rather agree with everything you've said there, and appreciate why a cache would need to be warmed in an identical state. Your point about the images potentially being stored externally also rather nails the validity for redirection being necessary. (It's not even slow doing this!)

I'm pretty much inclined at this point to say the SEO will just have to deal with it. :)

Thanks for the rokka.io suggestion too. I'll look into that to see if it has anything to offer.

**Comment by dbu** [comment]
> and appreciate why a cache would need to be warmed in an identical state. Your point about the images potentially being stored externally also rather nails the validity for redirection being necessary. (It's not even slow doing this!)

if you can figure out your cache warming to do the exact configuration that is then used in the rendered page, the page would be rendered with the direct links to the images. but it will be a bit tricky to get that right and difficult to keep things in sync.
