### ISSUE TITLE
2.12.2 autowiring of  Imagine\Image\ImagineInterface broken

### ISSUE THREAD

**Issue by perice** [liip/LiipImagineBundle#1574]
When upgrading from 2.12.1 to 2.12.2, I get this error message:

Cannot autowire service "App\Imagine\Filter\Loader\AffineClamp2Filter": argument "$imagine" of method "__construct()" references interface "Imagine\Image\ImagineInterface" but no such service exists. You should maybe alias this interface to one of these existing services: "liip_imagine.gd", "liip_imagine.imagick", "liip_imagine.gmagick".

Sample code:

```
namespace App\Imagine\Filter\Loader;

use Imagine\Image\ImagineInterface;
use Liip\ImagineBundle\Imagine\Filter\Loader\LoaderInterface;

class AffineClamp2Filter implements LoaderInterface
{
    /**
     * @var ImagineInterface
     */
    protected $imagine;

    public function __construct(ImagineInterface $imagine)
    {
        $this->imagine = $imagine;
    }
}
```

Workaround:
Downgrade to 2.12.1

**Comment by dbu** [comment]
i think the issue comes from https://github.com/liip/LiipImagineBundle/pull/1561 where we tell symfony to auto-tag the interface. is your class configured as a service or was it before unused?

that change evaded the changelog, and i should have tagged a new minor version and not a patch version.

however, we should alias the ImagineInterface as a service anyways to help with autowiring, i will look into that now.

**Comment by dbu** [comment]
does #1583 solve the issue for you?
