### ISSUE TITLE
Provide image width and height in <img> html tag

### ISSUE THREAD

**Issue by ghost** [liip/LiipImagineBundle#2]
See https://github.com/avalanche123/AvalancheImagineBundle/issues/20

I will try to contribute the code for this later.

**Comment by scuben** [comment]
Is there any solution to this problem of getting the image dimension of the cached image?

**Comment by makasim** [comment]
You can resolve the url of cache image, then load the image content to php memory and get width and height using Imagine library for example, It is not optimal I must admit so you use it carefully.

I dont see any other solutions to it for now.

**Comment by juliengustin** [comment]
To resolve it, I created a twig filter : 

...
<?php 
// src/AppBundle/Twig/PhotoInfos.php
namespace AppBundle\Twig;

class PhotoInfos extends \Twig_Extension
{
    public function getFilters()
    {
        return array(
            new \Twig_SimpleFilter('height', array($this, 'heightFilter')),
        );
    }

    public function heightFilter($relativeSrc)
    {
        list($width, $height) = getimagesize($relativeSrc);
        return $height;
    }

    public function getName()
    {
        return 'photo_infos';
    }
}
...

In service.yml
....
app.twig_extension:
        class: AppBundle\Twig\PhotoInfos
        public: false
        tags:
            - { name: twig.extension }
....

And using it : 

...
<img src="{{ asset('img/'~project.photos.first.photoFileName)|imagine_filter('grid_list') }}" alt="l'heureux nouveau" width="302" height="{{ asset('img/'~project.photos.first.photoFileName)|imagine_filter('grid_list')|height }}"  />
...

**Comment by juliengustin** [comment]
To resolve it, I created a twig filter : 

```
<?php 
// src/AppBundle/Twig/PhotoInfos.php
namespace AppBundle\Twig;

class PhotoInfos extends \Twig_Extension
{
    public function getFilters()
    {
        return array(
            new \Twig_SimpleFilter('height', array($this, 'heightFilter')),
        );
    }

    public function heightFilter($relativeSrc)
    {
        list($width, $height) = getimagesize($relativeSrc);
        return $height;
    }

    public function getName()
    {
        return 'photo_infos';
    }
}
```

In service.yml
```
app.twig_extension:
        class: AppBundle\Twig\PhotoInfos
        public: false
        tags:
            - { name: twig.extension }
```

And using it : 

```
<img src="{{ asset('img/'~project.photos.first.photoFileName)|imagine_filter('grid_list') }}" alt="l'heureux nouveau" width="302" height="{{ asset('img/'~project.photos.first.photoFileName)|imagine_filter('grid_list')|height }}"  />
```

**Comment by silverbackdan** [comment]
I know this has been stale since 2015 but I just wanted to provide some clarity if people stumble across this answer as I have.

The issue with the controller solution here is if we decide that the cached images should be protected (for example, so only users who own the image are able to access it). In that instance the recommendation appears to be to create a custom controller which handles the permissions before resolving the file as detailed in 2016 here https://github.com/liip/LiipImagineBundle/issues/817#issuecomment-257194522

Using the solution to get the file data in this way is not longer a valid solution.

I am looking to have more information about the filtered image to give to a user as well. I'd like dimensions, mime type (easy enough to know from the original file) and also the file size.

I'm investigating hooking into getting the correct CacheResolver for the given filter to resolve the file. It may be that we aren't on a local filesystem and instead perhaps storing on S3, and then another file system for a different filter... I think there must be a way to do this whereby we resolve the cacheresolver for the folter and then can get the image. 🤞
