### ISSUE TITLE
Sometimes when production cache is being generated, resources directory is incorrect

### ISSUE THREAD

**Issue by axelvnk** [liip/LiipImagineBundle#689]
[Twig_Error_Loader] The "[...]/vendor/liip/imagine-bundle/Liip/ImagineBundle/Resources/views" directory does not exist

After a few cache clears it reappears..  I'm on version ~1.2, using it with Sylius.
The correct directory is vendor/liip/imagine-bundle/Resources/views

**Comment by Richtermeister** [comment]
:+1: Running into this as well, for me this happens when I load the api doc page (powered by NelmioApiDocBundle), in dev and production mode. Other page loads don't seem to trigger it.

**Comment by makasim** [comment]
I dont have any idea what this happens. I am really curious.

**Comment by michellesanver** [comment]
@axelvnk @Richtermeister I am going through all issues to sort and prioritise. Is this still an issue for you? I am aware that a lot of people stopped using NelmioApiDocBundle etc. Since this is so old, please open a new issue if that is the case, referencing this issue, and we will prioritise accordingly. Thanks a lot! :)

**Comment by Richtermeister** [comment]
@michellesanver thanks for checking. Have not used NelmioApiDocBundle in a while, closing this sounds good. 👍
