### ISSUE TITLE
Url is still http in https

### ISSUE THREAD

**Issue by pDc-** [liip/LiipImagineBundle#727]
Hi, 

This is my problem : My website is in https but the urls generated by imagine_filter are in http.

I don't know how to solve that.

Maybe is there any parameter to configure to make it work ?

**Comment by mitrae** [comment]
What value do you have for `framework.assets.base_urls` ?

**Comment by pDc-** [comment]
Hi mitrae,

I didn't configure this. 

I tried to set 'https://my.domain.com' but the problem is the same unfortunately.

**Comment by mitrae** [comment]
what symfony version are you using?

starting from 2.7: `
framework:
    templating:
        assets_version: 'v5'
        assets_version_format: '%%s?version=%%s'
        assets_base_urls:
            http: ['http://cdn.example.com']
            ssl:  ['https://secure.example.com']
`

**Comment by pDc-** [comment]
I'm using 2.8.3.

So I tried to add :
>framework:
>    assets:
>        base_urls: ['https://my.domain.com']

And nothing happened.

**Comment by mitrae** [comment]
Seems imagine_filter ignores this parameter. This filter by itself generates absolute url

**Comment by makasim** [comment]
@pDc- what resolve do you use? s3, local or?

**Comment by pDc-** [comment]
Hi makasim,

I'm using the default resolver so does it call the WebPathResolver in the Bundle ? 

I tried to define router.request_context.scheme as https in parameters.yml but nothing changed.

**Comment by makasim** [comment]
The router is used internally.

**Comment by makasim** [comment]
https://github.com/liip/LiipImagineBundle/blob/master/Imagine/Cache/Resolver/WebPathResolver.php#L137

**Comment by pDc-** [comment]
Yes, I took a look at this. That's why I tried to define router.request_context.scheme.

What am I doing wrong ? Should I declare another Resolver in the config ? 

Here is my basic configuration of the Bundle : 

liip_imagine:
    resolvers:
       default:
          web_path: ~

    filter_sets:
        cache: ~
        thumbpic:
            quality: 75
            filters:
                thumbnail: { size: [40, 40], mode: outbound }

**Comment by makasim** [comment]
when http request is coming symfony rewrites it with actual request options. That's why this parameters do not work

Parameters are only make sense for cli commands.

**Comment by makasim** [comment]
I suspect that the request coming is http itself. Check this first.

**Comment by pDc-** [comment]
Ok thanks for your answers ! 
I'm going to check this then. Maybe that's because I'm behind a HA Proxy. 
I'll ask to the administrator. 

I'll keep you in touch soon.

**Comment by pDc-** [comment]
Hi !

Thank you so much for your help. It was a problem with the server as you suspected @makasim .
The proxy was correctly configured but the server wasn't.

I'm sorry for disturbance.. 

I can close the issue.

Thanks again for your help @makasim and @mitrae  !

**Comment by jfl51** [comment]
cool







Jean-François LANDANSKI
Responsable Bureau d'étude
jean-francois.landanski@jvs.fr
Tél. : 03 26 65 21 26 - Fax : 03 26 70 57 26
www.jvs-is.fr 
<http://lsi.jvsonline.fr/r/32/52b58b65-0a89-4240-a640-042d8f2876a5/undefined>



 <http://lsi.jvsonline.fr/r/33/ae9231a8-8560-4b3c-8496-b8e0eda714ac/undefined>De : pDc- [mailto:notifications@github.com]Envoyé : jeudi 21 avril 2016 10:33À : liip/LiipImagineBundle <LiipImagineBundle@noreply.github.com>Cc : jfl51 <jfl@jvs.fr>; Manual <manual@noreply.github.com>Objet : Re: [liip/LiipImagineBundle] Url is still http in https (#727)Hi !Thank you so much for your help. It was a problem with the server as yoususpected @makasim <https://github.com/makasim>  .The proxy was correctly configured but the server wasn't.I'm sorry for disturbance..I can close the issue.Thanks again for your help @makasim <https://github.com/makasim>  and@mitrae <https://github.com/mitrae>  !—You are receiving this because you are subscribed to this thread.Reply to this email directly or view it on GitHub<https://github.com/liip/LiipImagineBundle/issues/727#issuecomment-212807033><https://github.com/notifications/beacon/AO8i0ybiLMEtwyqhaGXzyEvI_Dp57IrHks5p5zYpgaJpZM4IIL_j.gif>

**Comment by makasim** [comment]
np

**Comment by rsnitsch** [comment]
What to do about this if you're behind a reverse proxy handling the HTTPS stuff and dispatching the requests as HTTP to various Docker containers running the actual Symfony application?

Is there a way to force the generated asset urls to be HTTPS?

**Comment by DennisdeBest** [comment]
I am running my symfony 4.3 app in a docker container with Traefik reverse proxy and all images using the liip imagine filter are served over http instead of https.

I haven't found a way to get this to work correctly, any help would be greatly appreciated

**Comment by makasim** [comment]
https://symfony.com/doc/current/deployment/proxies.html

**Comment by DennisdeBest** [comment]
Thanks for the fast reply I'm going to look into that right now

**Comment by DennisdeBest** [comment]
I have been searching for ages and didn't think of this ...
anyway setting :
TRUSTED_PROXIES=127.0.0.1, 172.20.0.0/8 
in my .env.local fixed the issues
thanks a million
