### ISSUE TITLE
This library have a version who can work outside Symfony?

### ISSUE THREAD

**Issue by AxelBriche** [liip/LiipImagineBundle#862]
Hello, this library have a version who can work outside Symfony and with local and remote image-url please?

**Comment by cedricziel** [comment]
I think you may find a substitute in [Glide](http://glide.thephpleague.com/) it can work with sources through flysystem so that should have you covered.

Other than that - you could assemble the parts yourself. You can get an insight on how everything is structured through configuration and the CompilerPasses. But I doubt it's worth the hassle.
