### ISSUE TITLE
How debug a custom filter ?

### ISSUE THREAD

**Issue by raphaelriehl** [liip/LiipImagineBundle#878]
| Q | A
| --- | ---
| Bug Report? | no
| Feature Request? | no
| BC Break Report? | no
| RFC? | yes
| Imagine Bundle Version | 1.7

First, thanks for this amazing bundle !
I have question for my custom filter... how i can debug this ?
My custom filter is well applied on my images, but i don't know how i can debug this.

**Comment by cedricziel** [comment]
You can debug the bundle functionality like any other php application: through a debugger like [xdebug](https://xdebug.org/).

Your IDE should have support for debugging php applications, but most PHP IDEs do. For reference, here is an article using PHPStorm: https://www.jetbrains.com/help/phpstorm/2016.3/debugging-php-applications.html

When applied, you should be able to set breakpoints in most places and inspect the stack directly in your IDE.

I'm going to close this issue, since I think it's more general about debugging php applications than specific issues with the bundle itself.

Chances are I got your question wrong. - If so, please don't hesitate to tell us more about your question! :smile:

**Comment by raphaelriehl** [comment]
More exactly, i want intercept information when my cache is generated with my new filter.

I would like to know where or when exactly my filter is executed for listen an eventual exception or information with var_dump, for example.

> I'm going to close this issue, since I think it's more general about debugging php applications than specific issues with the bundle itself.

Yes and no... When i use a var_dump in most php file in Symfony who are called in the process, this is displaying when i call my page in my web browser or in network request of my inspector.
But with this filter i have no idea to read var_dump in the logical process.

But you're right, i have never studied how to debug properly with my IDE.

If i configure correctly my IDE and Xdebug it's possible to intercept my var_dump in my filter without another manipulation ? And this information will be displayed in my IDE ?
I have find this documentation (in french sorry): https://tech.acseo.co/debugger-vos-developpements-php-xdebug-atom/

PS: Sorry for my english.

**Comment by cedricziel** [comment]
No need to apologize :)

`var_dump` is only able to capture the state of a pointer reference, but doesn't really have much for you to give. In fact I'd consider using `var_dump` (or the `dump` function and filter to expand on it) useful for exactly one purpose: Evalutating a datastructure and letting me see through it. - If you want to have a closer look at sequences or the state mutations, i strongly suggest you read up on that.

There's a free [laracasts episode](https://laracasts.com/index.php/series/how-to-be-awesome-in-phpstorm/episodes/19) that can show you what it might look like to debug your code visually.

**Comment by raphaelriehl** [comment]
Ok I will be documenting on this subject. Thanks for your answers.
