### ISSUE TITLE
[RFC] Split suggested dependencies into their own packges/repos

### ISSUE THREAD

**Issue by robfrawley** [liip/LiipImagineBundle#921]
| Q | A
| --- | ---
| Bug Report? | no
| Feature Request? | yes
| BC Break Report? | no
| RFC? | yes
| Imagine Bundle Version | 2.0

I have recently read a bunch of articles like "[There's no such thing as an optional dependency](https://php-and-symfony.matthiasnoback.nl/2014/04/theres-no-such-thing-as-an-optional-dependency/)" that assert having "suggested dependencies" is difficult from the consumer (or developer) standpoint and many recent issues (such as https://github.com/liip/LiipImagineBundle/issues/906#issuecomment-294812453) show this to be true.

One solution is to break the package into separate ones that all explicitly define their dependencies. For example, we might have `liip/imagine-bundle` and `liip/imagine-fly-system` and `liip/imagine-mongo` etc... There would be quite a few additional ones too, obviously.

Such an approach would require some initial setup help from @liip due to the requirement of separate Git repositories. @lsmith77 Before I spend any more time playing with this on my own, is there any interest in pursuing such an approach?

**Comment by cedricziel** [comment]
Hmm. Interesting. While I think that's true, those dependencies (especially the ones in the linked comment) are really optional to the user from the point of view where we still provide a functional bundle.

If we split, people will inevitably ask why their feature is not available as well - I don't think that would change much.

Just my 2cts, but I think a split would produce such optional dependencies as well, rendering a split pretty useless - what do you think?

**Comment by antoligy** [comment]
Subtree split, so we distribute separately?  I'm a little worried about the few of us trying to maintain a greater number of repositories, unless we refer everything back to this one?

**Comment by lsmith77** [comment]
I see this topic mostly from a maintainer point of view. I have very little sympathy for people that count lines in their vendor dir (though there is one dimension where I do see where such people come from if they actually code review every line of code in the vendor dir).

So to me splitting up only make sense if we can ease the in maintenance, by making it easier to give ownership to more people, or by reducing effort in QA'ing releases because each package contains less code.

**Comment by robfrawley** [comment]
It seems the general view from @cedricziel and @antoligy is that this would greater maintenance for the already strained maintainers; a core requirement such a change would need to improve for both myself and @lsmith77. So, let's close this for the time being. Thanks for your thoughts everyone!

**Comment by makasim** [comment]
IMO it does not worth it. The code we are about to split is too small (one or few classes). If we do that it would be harder for developers\maintainers to add features, fix bugs, do refactoring since we would have to introduce changes to several packages (install them, link, configure and so on).

For bigger things it might make sense though.
