### ISSUE TITLE
Yaml file extension

### ISSUE THREAD

**Issue by Hashiko** [liip/LiipImagineBundle#961]
| Q | A
| --- | ---
| Bug Report? | yes
| Feature Request? | yes
| BC Break Report? | yes
| RFC? | no
| Imagine Bundle Version | 1.8.0

The .yaml extension is not supported in Symfony 2.4 and 2.5. The extension of the yaml configuration files and routing files should have the .yml which is supported by all Symfony version since its introduction.

**Comment by robfrawley** [comment]
Symfony `2.4` and `2.5` are EOL, and have been since January 2015 and July 2015, respectively (meaning they haven't received any backported features or security fixes since them, and should not, IMHO, be used in production). We currently support Symfony `2.3`, `2.7`, `2.8`, and `3.x`.

**Comment by robfrawley** [comment]
As a note, regardless of our official support, the project *may* work with other versions of Symfony. In the case of `2.4` and `2.5`, you can simply directly include the contents of [Resources/config/routing.yaml](https://github.com/liip/LiipImagineBundle/blob/1.0/Resources/config/routing.yaml) in your `app/config/routing.yml` file manually, instead of including it.
