### ISSUE TITLE
Services will become private by default starting from Symfony 3.4

### ISSUE THREAD

**Issue by rpkamp** [liip/LiipImagineBundle#998]
| Q | A
| --- | ---
| Bug Report? | no
| Feature Request? | no
| BC Break Report? | yes
| RFC? | no
| Imagine Bundle Version | 1.0 and 2.0

http://symfony.com/blog/new-in-symfony-3-4-services-are-private-by-default

Services that need to public need to explicitly marked as public starting from Symfony 3.4

**Comment by weaverryan** [comment]
But just to help: if there are some services that are public currently that do *not* need to be public in the future, you can leave them as-is: if a service doesn't specifically have `public="true"`, and a user tries to use it on Symfony 3.4, they will get a deprecation notice. In Symfony 4, it will become private.

**Comment by robfrawley** [comment]
I believe we have already caught all services that need to be marked public on the `2.0` branch; this issue was resolved weeks ago (do note that the `1.x` branch will not be Symfony `4.x` compatible).

Regardless, thanks for the attention @weaverryan from a real Symfony maintainer; it makes us feel special and warm inside. :-)
